### PR TITLE
Fix TabularEditor.drag_move to properly allow drag-copy 

### LINKED ISSUE #351: TabularEditor doesn't properly allow drag-copy
This looks like a bug here: https://github.com/enthought/traitsui/blob/master/traitsui/qt4/tabular_model.py#L315

I think that the fix is simple: return `QtCore.Qt.MoveAction | QtCore.Qt.CopyAction`.

### PR DESCRIPTION
**Pull request by kitchoi**
Fix #351 

~WIP for I would like to investigate:~
   ~(1) Adding tests~
   ~(2) Possibly same issue with TableEditor and ListStrEditor~

### CODE REVIEW

**Comment by corranwebster** [comment]
@kitchoi Would you be OK with this being merged in the next release, even though not as complete as you would like?

**Comment by kitchoi** [comment]
Yes I agree this would be worth merging.  Removing WIP in the title.

**Comment by kitchoi** [comment]
Yes I agree this would be worth merging.  Removing WIP in the title.

**Comment by corranwebster** [comment]
Thanks!

**Pull request merged**
