### PR TITLE
Replace use of history list with CommandStack and UndoManager.

### PR DESCRIPTION
**Pull request by corranwebster**
This is a drop-in replacement for `UndoHistory` that is _almost_ backwards compatible:
- other than test failures due to https://github.com/enthought/pyface/issues/883 and changes needed where code was looking at `UndoHistory` internals, all previous tests pass.
- the `history` trait is no-longer used, but hasn't been removed yet (looking for feedback on this; is it better to remove now, or later)

Likelihood of 3rd party code breakage is small: only if it is dealing with internals of the Undo/Redo mechanism, and I am not aware of any such code.

This should not be merged until Pyface#883 is merged.  In fact the test runs for this PR will probably fail until Pyface#883 is merged.

This is another step towards #1060.

### CODE REVIEW

**Comment by rahulporuri** [comment]
> This should not be merged until Pyface#883 is merged. In fact the test runs for this PR will probably fail until Pyface#883 is merged.

Not sure why CI is happy right now - but note that traitsui does not install pyface from source anymore. TraitsUI relies on the installed version of Pyface so if this PR requires pyface#883, it will need to wait for the pyface release.

**Comment by corranwebster** [comment]
> Not sure why CI is happy right now - but note that traitsui does not install pyface from source anymore.

That'd be why it's happy.  I put a pyface version check to skip a couple of the tests which are expected to fail on 7.2.0 or before.

So given that, I would expect that:

- tests run against 7.2.0 will pass (with skips)
- tests of this code run against current Pyface master will fail
- tests of this code run against Pyface master after enthought/pyface#883 is merged will pass

**Review by rahulporuri — APPROVED** [review]
LGTM.

**Comment by rahulporuri** [comment]
I've reviewed the PR - made a few recommendations - and i made those recommended changes to the PR. I think we can finally merge the PR.

**Pull request merged**
