### PR TITLE
Fix crash when number of columns changes

### LINKED ISSUE #894: TabularEditor crashes when reducing number of columns in adapter
I have a custom TabularAdapter that changes dynamically the number of columns in a TabularEditor based on the size of the underlying variable.

When I reduce the number of columns, I get this crash:

```
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.8.3.0\python-3.8.3.amd64\lib\site-packages\traitsui\qt4\tabular_editor.py", line 913, in columnResized
    self.resizeColumnsToContents()
  File "C:\WinPython-64bit-3.8.3.0\python-3.8.3.amd64\lib\site-packages\traitsui\qt4\tabular_editor.py", line 894, in resizeColumnsToContents
    widths = compute_column_widths(
  File "C:\WinPython-64bit-3.8.3.0\python-3.8.3.amd64\lib\site-packages\traitsui\helper.py", line 168, in compute_column_widths
    widths[i] = user_width
IndexError: list assignment index out of range
```

It seems the issue is with the user width array which is still of the wrong size.
I am submitting a PR that fixes this by resetting the user widths when there is a mismatch in size.

### PR DESCRIPTION
**Pull request by FedeMiorelli**
Fixes #894

### CODE REVIEW

**Comment by kitchoi** [comment]
@FedeMiorelli Thank you very much for the bug report and the fix!  I can confirm that this fixes the bug, and more than that. I think you are right that the `user_widths` needs resetting. That really solves the bulk of the problem.

There is a different place where we can reset the `user_widths` whenever the adapter `columns` changes, and that might be a better place than `columnResized`, which is called whenever the user manually adjusts the column widths as well.

It is possible that I have missed something. If you don't mind, could you please try the branch in https://github.com/enthought/traitsui/pull/897 and see if that also resolves the issue? 

Thanks again!

**Comment by FedeMiorelli** [comment]
@kitchoi Thanks for providing a better solution! Your branch works fine for me.
Cheers

**Comment by kitchoi** [comment]
@FedeMiorelli  #897 is now merged with you as a co-author. Thank you very much for your contribution!  I believe this PR can now be closed, is that alright?

**Comment by FedeMiorelli** [comment]
Thanks @kitchoi yes please go ahead and close this!
Cheers

**Comment by kitchoi** [comment]
Thank you!  Closing.

**Pull request closed without merging**
