### PR TITLE
Upgrade edm to use the latest version on CI - 3.3.0

### PR DESCRIPTION
**Pull request by rahulporuri**
This PR upgrades EDM to the latest available version - 3.3.0 - on the CI.

**Checklist**
- [ ] ~Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~ Not news-worthy.

### CODE REVIEW

**Comment by rahulporuri** [comment]
well that's disappointing. the setup edm action failed - 

```
Run enthought/setup-edm-action@v1
  with:
    edm-version: 3.3.0
    download-directory: ~/.cache/download
  env:
    INSTALL_EDM_VERSION: 3.3.0
    EDM_ROOT_DIRECTORY: /home/runner/work/traitsui/traitsui/.edm
Using directory for storing downloaded installer: /home/runner/.cache/download
/usr/bin/bash /home/runner/work/_actions/enthought/setup-edm-action/v1/dist/install-edm-linux.sh 3.3.0 /home/runner/.cache/download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   243    0   243    0     0   1327      0 --:--:-- --:--:-- --:--:--  1327
/home/runner/.cache/download/edm_cli_3.3.0_linux_x86_64.sh: line 1: syntax error near unexpected token `newline'
/home/runner/.cache/download/edm_cli_3.3.0_linux_x86_64.sh: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
(node:1570) UnhandledPromiseRejectionWarning: Error: The process '/usr/bin/bash' failed with exit code 2
    at ExecState._setResult (/home/runner/work/_actions/enthought/setup-edm-action/v1/dist/index.js:1026:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/enthought/setup-edm-action/v1/dist/index.js:1009:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/enthought/setup-edm-action/v1/dist/index.js:903:27)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Socket.<anonymous> (internal/child_process.js:444:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:675:12)
(node:1570) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1570) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

ref https://github.com/enthought/traitsui/runs/4403939868?check_suite_focus=true.

**Comment by mdickinson** [comment]
EDM 3.3.0 should be uploaded; closing and re-opening to test.

**Review by mdickinson — APPROVED** [review]
LGTM

**Comment by mdickinson** [comment]
Looks like we have the same Big Sur / EDM PySide2 issue as on Envisage and Pyface.

**Pull request merged**
