### PR TITLE
Fix downgrading to traits 6.0 for CI environment

### LINKED ISSUE #616: Pandas 0.24 CI issues
Pandas 0.24 seems to cause problems with CI for Linux under Python 3.6 and PyQt5. Possibly also under Windows.  The DataFrameEditor would be the proximate cause.

### LINKED ISSUE #934: Enable brings in Traits 6.0 instead of 6.1 into CI environment
Enable is a dependency of Chaco, which was added as a test dependency to allow automatic testing of examples. It is used by one example `examples/demo/Useful/demo_group_size.py`.

The easiest "fix" would be to exclude this example from automatic testing.

A proper fix would need to modify installation code in `etstool.py`, and I'm not sure what would be the best way to do that in order to have a consistent set of packages.

### PR DESCRIPTION
**Pull request by kitchoi**
Fix #934. 
Closes #616 as well.

The reason why bringing in enable (via chaco) into the test dependencies causes traits 6.0 to be installed is that there is an additional constraint on the pandas version. This changes the eventual dependency solver results such that traits 6.0 was installed instead of traits 6.1

By removing the constraint, the CI environment is installing a newer version of pandas (0.25), and a newer version of traits (6.1).

This PR also fixes wx CheckListEditor dispose logic because the tests are failing with Traits 6.1.0. The dispose logic was incorrect, but it wasn't revealed until we upgrade.

For the record, I think TraitsUI master has not dropped support for Traits 6.0. It is just CI is only targeting one version, we have been using the latest. Arguments can be made that we should be testing against the minimum supported versions of traits as well.

### CODE REVIEW

**Comment by kitchoi** [comment]
For the record, this error from CI on Wx and Windows has been around for some time even before this PR:
```
======================================================================
ERROR: traitsui.tests.ui_editors.test_data_frame_editor (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: traitsui.tests.ui_editors.test_data_frame_editor
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\unittest\loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\unittest\loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\ui_editors\test_data_frame_editor.py", line 15, in <module>
    from pandas import DataFrame
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas/_libs/tslibs/conversion.pxd", line 11, in init pandas._libs.tslib
  File "pandas/_libs/tslibs/conversion.pyx", line 40, in init pandas._libs.tslibs.conversion
  File "pandas/_libs/tslibs/parsing.pyx", line 44, in init pandas._libs.tslibs.parsing
  File "pandas/_libs/tslibs/ccalendar.pyx", line 16, in init pandas._libs.tslibs.ccalendar
  File "pandas/_libs/tslibs/strptime.pyx", line 605, in init pandas._libs.tslibs.strptime
  File "pandas/_libs/tslibs/strptime.pyx", line 521, in pandas._libs.tslibs.strptime.TimeRE.__init__
  File "pandas/_libs/tslibs/strptime.pyx", line 396, in pandas._libs.tslibs.strptime.LocaleTime.__init__
  File "pandas/_libs/tslibs/strptime.pyx", line 354, in pandas._libs.tslibs.strptime._getlang
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: en-US
```

**Comment by kitchoi** [comment]
These two on wx + Windows are new (I think), will investigate:
```
======================================================================
ERROR: test_custom_editor_checklist_values_change_dispose (traitsui.tests.editors.test_check_list_editor.TestCheckListEditorMapping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_check_list_editor.py", line 321, in test_custom_editor_checklist_values_change_dispose
    self.check_checklist_values_change_after_ui_dispose("custom")
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_check_list_editor.py", line 263, in check_checklist_values_change_after_ui_dispose
    model.possible_values = ["two", "one"]
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\_tools.py", line 68, in store_exceptions_on_all_threads
    raise exceptions[0]
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traits\trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traits\trait_notifiers.py", line 616, in dispatch
    handler(*args)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\editor.py", line 239, in _list_updated
    self.list_updated(self.list_value())
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\check_list_editor.py", line 116, in list_updated
    self.rebuild_editor()
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\check_list_editor.py", line 169, in rebuild_editor
    panel.SetSizer(None)
AttributeError: 'NoneType' object has no attribute 'SetSizer'
======================================================================
ERROR: test_simple_editor_checklist_values_change_dispose (traitsui.tests.editors.test_check_list_editor.TestCheckListEditorMapping)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_check_list_editor.py", line 318, in test_simple_editor_checklist_values_change_dispose
    self.check_checklist_values_change_after_ui_dispose("simple")
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_check_list_editor.py", line 263, in check_checklist_values_change_after_ui_dispose
    model.possible_values = ["two", "one"]
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\_tools.py", line 68, in store_exceptions_on_all_threads
    raise exceptions[0]
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traits\trait_notifiers.py", line 522, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traits\trait_notifiers.py", line 616, in dispatch
    handler(*args)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\editor.py", line 239, in _list_updated
    self.list_updated(self.list_value())
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\check_list_editor.py", line 116, in list_updated
    self.rebuild_editor()
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\check_list_editor.py", line 122, in rebuild_editor
    control.Clear()
AttributeError: 'NoneType' object has no attribute 'Clear'
```

**Comment by kitchoi** [comment]
The two tests above in `traitsui.tests.editors.test_check_list_editor.TestCheckListEditorMapping` pass after downgrading to traits 6.0.0.
It seems to be related to https://github.com/enthought/traits/issues/1233 where we noticed reference cycles in `TraitListObject`.
Adding `import gc; gc.collect()` after the UI is disposed and before setting `model.possible_values` allow the tests to pass (That is *not* the fix, but just to show it being related to reference counts):
https://github.com/enthought/traitsui/blob/b400c447d2481c8be23ed6af9885cfd88998dbe6/traitsui/tests/editors/test_check_list_editor.py#L259-L263

The editor in Wx has been relying on garbage collections for silencing on_trait_change handlers. That needs to be fixed.

**Comment by rahulporuri** [comment]
I noticed this interesting exception on the wx expected failure on linux - https://travis-ci.org/github/enthought/traitsui/jobs/705428637 - 

```
======================================================================
ERROR: traitsui (unittest.loader._FailedTest)
----------------------------------------------------------------------
Traceback (most recent call last):

  File "/home/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/traitsui/__init__.py", line 55, in load_tests
    from traitsui.tests._tools import filter_tests

  File "/home/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/traitsui/tests/_tools.py", line 25, in <module>
    from pyface.api import GUI

  File "/home/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/api.py", line 12, in <module>
    from .about_dialog import AboutDialog

  File "/home/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/about_dialog.py", line 15, in <module>
    from .toolkit import toolkit_object

  File "/home/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/toolkit.py", line 23, in <module>
    toolkit = toolkit_object = find_toolkit("pyface.toolkits")

  File "/home/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/base_toolkit.py", line 269, in find_toolkit
    return import_toolkit(ETSConfig.toolkit, entry_point)

  File "/home/travis/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/base_toolkit.py", line 233, in import_toolkit
    raise RuntimeError(msg)

RuntimeError: No pyface.toolkits plugin could be loaded for wx
----------------------------------------------------------------------
```

I don't know if that is the original reason why we were skipping tests for wx toolkit.

**Comment by rahulporuri** [comment]
I'm also seeing this error (other than `ERROR: traitsui.tests.ui_editors.test_data_frame_editor (unittest.loader._FailedTest)`)

```
======================================================================
FAIL: test_color_column (traitsui.tests.test_color_column.TestColorColumn)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\test_color_column.py", line 48, in test_color_column
    with store_exceptions_on_all_threads(), create_ui(data):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\_tools.py", line 186, in create_ui
    ui = object.edit_traits(**ui_kwargs)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traits\has_traits.py", line 1678, in edit_traits
    args,
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\view.py", line 462, in ui
    ui.ui(parent, kind)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\ui.py", line 246, in ui
    self.rebuild(self, parent)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\toolkit.py", line 125, in ui_live
    ui_live.ui_live(ui, parent)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\ui_live.py", line 52, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\ui_live.py", line 88, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\ui_base.py", line 71, in display_ui
    ui.owner.init(ui, parent, style)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\ui_live.py", line 203, in init
    sw = panel(ui, window)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\ui_panel.py", line 272, in panel
    panel, content[0], ui
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\ui_panel.py", line 431, in fill_panel_for_group
    panel, group, ui, suppress_label, is_dock_window, create_panel
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\ui_panel.py", line 587, in __init__
    self.add_items(content, panel, self.sizer)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\ui_panel.py", line 908, in add_items
    editor.prepare(item_panel)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\editor.py", line 264, in prepare
    self.init(parent)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\table_editor.py", line 200, in init
    self._create_toolbar(panel, sizer)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\wx\table_editor.py", line 456, in _create_toolbar
    sizer.Add(tb_sizer, 0, wx.ALIGN_RIGHT | wx.EXPAND)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" failed at ..\..\src\common\sizer.cpp(2089) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored with wxEXPAND
----------------------------------------------------------------------
Ran 320 tests in 8.819s
FAILED (failures=1, errors=1, skipped=156)
```

**Comment by kitchoi** [comment]
@rahulporuri Yep, those errors have been around for quite some time already.

**Comment by kitchoi** [comment]
The last one probably can be fixed together with #889.

As for the `No pyface.toolkits plugin could be loaded for wx`, I bet `import wx` fails, e.g. if the Travis image has upgraded such that it no longer works this build:
https://github.com/enthought/traitsui/blob/1a49a9ac28ffab5a4dd7e904a9aa9cda81ceb901/etstool.py#L203

**Pull request merged**
