### PR TITLE
Add missing calls to super class "__init__"s

### PR DESCRIPTION
**Pull request by rahulporuri**
This PR adds missing calls to `super().__init__()` in a few classes which overrided `__init__` methods of their base classes.

**Checklist**
- [ ] Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)

### CODE REVIEW

**Comment by rahulporuri** [comment]
One of the CI jobs failed with the following weird/cryptic message while running the integration tests. Restarting the jobs to see if this is intermittent.

```
Command '['edm', 'run', '-e', 'traitsui-test-3.6-pyside2', '--', 'python', '-W', 'default', '-m', 'unittest', 'discover', '-v', '/home/runner/work/traitsui/traitsui/integrationtests']' returned non-zero exit status 252.
```

**Comment by aaronayres35** [comment]
> One of the CI jobs failed with the following weird/cryptic message while running the integration tests. Restarting the jobs to see if this is intermittent.
> 
> ```
> Command '['edm', 'run', '-e', 'traitsui-test-3.6-pyside2', '--', 'python', '-W', 'default', '-m', 'unittest', 'discover', '-v', '/home/runner/work/traitsui/traitsui/integrationtests']' returned non-zero exit status 252.
> ```

This just happened on #1674 as well... 🤔

**Review by aaronayres35 — APPROVED** [review]
LGTM

My only question is how did you decide where to place the call to super within the body of the method?

**Comment by rahulporuri** [comment]
> My only question is how did you decide where to place the call to `super` within the body of the method?

I was trying to do it as close to the top of the method as possible - while also setting any arguments on the class that were passed through.

**Comment by rahulporuri** [comment]
@aaronayres35 given your comment, i went with a slightly different approach to this PR - i passed the incoming arguments to the super `__init__` call - instead of setting it on the object in the `__init__` method. This new approach feels like the right thing to do - and is something i've seem elsewhere as well.

**Comment by rahulporuri** [comment]
given the changes, would you like to do another review of this PR @aaronayres35

**Review by aaronayres35 — APPROVED** [review]
Still LGTM, thank you!

**Pull request merged**
