### PR TITLE
Remove use of traits._py2to3 module

### PR DESCRIPTION
**Pull request by rahulporuri**
because all version of python we support have str.find, we don't need to use the private module.

note that str_find and str_rfind are being removed from the private module in traits. see https://github.com/enthought/traits/pull/449

### CODE REVIEW

**Comment by rahulporuri** [comment]
The CI failures in this PR are similar to those in #493 
They are related to the jobs which test against pyside2. See traceback below 

```
Running tests in 'traitsui-test-3.6-pyside2'
copying file to tempdir: .coveragerc
[EXECUTING] edm run -e traitsui-test-3.6-pyside2 -- coverage run -p -m nose.core -v traitsui.tests --nologcapture
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
Command '['edm', 'run', '-e', 'traitsui-test-3.6-pyside2', '--', 'coverage', 'run', '-p', '-m', 'nose.core', '-v', 'traitsui.tests', '--nologcapture']' returned non-zero exit status 250
```

**Comment by mdickinson** [comment]
> sigh. `str.find` and `string.find` work differently. one works with unicode input and the other doesn't.

Right, I think we really want to use `lambda s: s.find` and `lambda s: s.rfind`.  Though _actually_ what we want to do is burn the `_split` method that uses this stuff. (The `str.partition` and `str.rpartition` methods would be useful here.)

**Comment by rahulporuri** [comment]
Merged master into this PR and CI is now green.

**Comment by mdickinson** [comment]
Still LGTM

**Comment by rahulporuri** [comment]
Thanks @corranwebster !

**Pull request merged**
