### PR TITLE
updated edm version in travis and appveyor config files

### LINKED ISSUE #1025: Use the latest EDM version (3.0.1)
A new major version of EDM is available and it would be good to update to the latest version - https://assets.enthought.com/downloads/edm/. This should be as simple as updating the environment variables in travis and appveyor config files.

https://github.com/enthought/traitsui/blob/6fccc3966e89a8082aace9623b84a80a74c46f3e/.travis.yml#L13
https://github.com/enthought/traitsui/blob/6fccc3966e89a8082aace9623b84a80a74c46f3e/appveyor.yml#L9

### PR DESCRIPTION
**Pull request by aaronayres35**
fixes #1025

### CODE REVIEW

**Comment by rahulporuri** [comment]
@aaronayres35 it looks like the CI is failing. Can you try to fix that?

**Comment by kitchoi** [comment]
Given this only occurs on linux, this may indeed have to do with the change to defaulting to "rh7" for Linux systems (that includes Debian and friends 🤯 ), Rahul has already mentioned in https://github.com/enthought/traitsui/issues/1025#issuecomment-660450157.
The PyQt4 egg may not be available in the repository for RH7?

For your reference, the available platforms depend on which platform you are on.
On Mac, if I do `edm install --help`, I can see the only option for `--platform` is "osx_x86_64".
On Linux, I can see "rh5_x86 | rh6_x86 | rh7_x86 | rh5_x86_64 | rh6_x86_64 | rh7_x86_64" being options allowed for the `--platform` flag.

**Comment by rahulporuri** [comment]
> https://github.com/enthought/traitsui/pull/1049#issuecomment-662339008

we should be able to confirm using packages.enthought.com/ui

**Comment by aaronayres35** [comment]
> > The PyQt4 egg may not be available in the repository for RH7?
> 
> we should be able to confirm using https://packages.enthought.com/ui

I saw this 
```
[EXECUTING] edm install -y -e traitsui-test-3.6-pyqt pyqt<4.12 h5py pytables pip coverage docutils configobj pandas chaco nose apptools numpy pygments traits
631Fetching indices for package repositories.. done
632No candidate found for requirement 'pyqt < 4.12-0'
``` 
in the build.
On  https://packages.enthought.com/ui it looks like for python 3.6 there is an egg for rh7-x86_64 for pyqt-4.12.1-1, but not for  pyqt < 4.12-0

**Comment by aaronayres35** [comment]
> I saw this
> 
> ```
> [EXECUTING] edm install -y -e traitsui-test-3.6-pyqt pyqt<4.12 h5py pytables pip coverage docutils configobj pandas chaco nose apptools numpy pygments traits
> 631Fetching indices for package repositories.. done
> 632No candidate found for requirement 'pyqt < 4.12-0'
> ```
> 
> in the build.

Also, in etstool.py I see 
```
extra_dependencies = {
    # XXX once pyside2 is available in EDM, we will want it here
    'pyside2': set(),
    'pyqt': {'pyqt<4.12'},  # FIXME: build of 4.12-1 appears to be bad
    'pyqt5': {'pyqt5'},
    # XXX once wxPython 4 is available in EDM, we will want it here
    'wx': set(),
    'null': set()
}
```
What is bad about  4.12-1?  Is pyqt-4.12.1-1 okay?

**Comment by kitchoi** [comment]
This is a case where we should have open an issue for when we did certain things out of the ordinary...
This came up quite recently https://github.com/enthought/traitsui/pull/971#discussion_r452204983

**Comment by kitchoi** [comment]
(For the record, in that PR it might appear that I _added_ the comment, but I was actually restoring a comment.)

**Comment by aaronayres35** [comment]
> This is a case where we should have open an issue for when we did certain things out of the ordinary...
> This came up quite recently [#971 (comment)](https://github.com/enthought/traitsui/pull/971#discussion_r452204983)

Just saw this, disregard my last commit.

**Comment by kitchoi** [comment]
This is weird... the last Travis CI job still sees `pyqt<4.12` requirement (and fails there) despite it being changed to `4.12.1-1` in the last commit. What did I miss?

**Comment by rahulporuri** [comment]
looks like CI is still failing when it is trying to create the etsdemo environment

**Comment by rahulporuri** [comment]
looks like CI is complaining about flake8 issues in `etstool.py`

**Pull request merged**
