### PR TITLE
Add links to API docs in a etsdemo examples for traitsui standard editors

### PR DESCRIPTION
**Pull request by rahulporuri**
This PR adds ReST links to API docs for editors in the contributed etsdemo examples for traitsui standard editors.

Note : I originally assumed that when clicked on the link, the user would simply be redirected to their default browser and the link API docs link would be opened in the browser. Interestingly, i'm not sure how but the API doc is rendered in the middle pane of the etsdemo application. This leads to the slightly awkward behavior where the user cant go back to read the module docstring/description if they open the link - unless they view a different example.

The user can still right-click on the link to copy the link and open it in a browser of their choice.

api-docs-in-etsdemo

### CODE REVIEW

**Comment by rahulporuri** [comment]
> This leads to the slightly awkward behavior where the user cant go back to read the module docstring/description if they open the link - unless they view a different example.

The awkward behavior I described above can be seen here - 

awkward-cant-click-back

**Comment by corranwebster** [comment]
I think you want `open_externally = True` in the `HTMLEditor` used by the etsdemo app to get the behaviour you want:

https://github.com/enthought/traitsui/blob/4033285b21a5e74e27582502b2321c71aee85558/traitsui/editors/html_editor.py#L68-L69

**Review by aaronayres35 — COMMENTED** [review]
After pulling in the changes made in #1446, when I run etsdemo with pyside2 on this branch I see this Error:
<details>

```
$ etsdemo
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
2020-12-16 10:27:51.142 Python[46247:1054271] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)
Traceback (most recent call last):
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/tree_editor.py", line 944, in _on_tree_sel_changed
    parent=editor, view=view, kind="subpanel"
  File "/Users/aayres/.edm/envs/something/lib/python3.6/site-packages/traits/has_traits.py", line 1678, in edit_traits
    args,
  File "/Users/aayres/Desktop/traitsui/traitsui/view.py", line 462, in ui
    ui.ui(parent, kind)
  File "/Users/aayres/Desktop/traitsui/traitsui/ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/toolkit.py", line 147, in ui_subpanel
    ui_panel.ui_subpanel(ui, parent)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 62, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 68, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 130, in __init__
    self.control = panel(ui)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 259, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 555, in __init__
    self._add_splitter_items(content, splitter)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 650, in _add_splitter_items
    panel = self._add_items([item])
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/ui_panel.py", line 891, in _add_items
    editor.prepare(inner)
  File "/Users/aayres/Desktop/traitsui/traitsui/editor.py", line 236, in prepare
    self.init(parent)
  File "/Users/aayres/Desktop/traitsui/traitsui/qt4/html_editor.py", line 59, in init
    page.setLinkDelegationPolicy(QtWebKit.QWebPage.DelegateAllLinks)
AttributeError: 'PySide2.QtWebEngineWidgets.QWebEnginePage' object has no attribute 'setLinkDelegationPolicy'
```

</details>

Without the change form #1446 everything works fine with pyside2, I just see the strange behavior you described.

**Comment by kitchoi** [comment]
> After pulling in the changes made in #1446, when I run etsdemo with pyside2 on this branch I see this Error:

That particular line is using an API in QtWebKit that is not available in QtWebEngine.
https://doc.qt.io/qt-5/qtwebenginewidgets-qtwebkitportingguide.html

Currently `pyface.qt.QtWebKit` uses `QtWebEngine` if it is available, but the API of QtWebEngine does not match QtWebKit exactly. Could you open a separate issue for this please?

**Comment by aaronayres35** [comment]
> Currently `pyface.qt.QtWebKit` uses `QtWebEngine` if it is available, but the API of QtWebEngine does not match QtWebKit exactly. Could you open a separate issue for this please?

Opened #1448

**Comment by kitchoi** [comment]
Thank you!

**Review by aaronayres35 — APPROVED** [review]
LGTM!  Aside from one editor missing a link

I tested with `pyside2` and I am no longer seeing errors mentioned previously (that fix was orthogonal to this PR).  I check the links and they all work correctly / everything looks good.  

I noticed there is no link for the DataFrameEditor demo, I think the link should be https://docs.enthought.com/traitsui/api/traitsui.ui_editors.data_frame_editor.html?highlight=dataframeeditor#traitsui.ui_editors.data_frame_editor.DataFrameEditor

**Comment by rahulporuri** [comment]
> I noticed there is no link for the DataFrameEditor demo, I think the link should be https://docs.enthought.com/traitsui/api/traitsui.ui_editors.data_frame_editor.html?highlight=dataframeeditor#traitsui.ui_editors.data_frame_editor.DataFrameEditor

Fixed. Merging.

**Pull request merged**
