### PR TITLE
TST: Add tests for ui_traits module

### PR DESCRIPTION
**Pull request by kitchoi**
This PR adds unit tests for the `ui_traits` module. 

Trait types and objects defined in this module are probably indirectly tested in places with more dependencies (e.g. integration tests). This PR adds unit tests that have very minimal dependency, making it easier to maintain.

### CODE REVIEW

**Comment by kitchoi** [comment]
I did not try to go for full coverage: This was motivated by the effort in trying to resolve deprecation warnings.

**Comment by rahulporuri** [comment]
> I did not try to go for full coverage:

Do you think it makes sense to create an issue to add the rest of the tests?

**Comment by kitchoi** [comment]
> Do you think it makes sense to create an issue to add the rest of the tests?

Up to you. For me, I add tests based on needs, e.g. when I need to make a change to something that does not have good tests. In this case, I added the tests because of a recent PR.

**Comment by kitchoi** [comment]
> In this case, I added the tests because of a recent PR.

To clarify, that is the PR(s) for resolving the deprecation warnings. Therefore I added enough tests to verify for myself that the deprecation warnings are resolved.

**Pull request merged**
