### PR TITLE
BUG: Fix broken insert_child on TreeNode

### LINKED ISSUE #559: Fix TreeNode.insert_child throwing TypeError
[`TreeNode.insert_child`](https://github.com/enthought/traitsui/blob/master/traitsui/tree_node.py#L246) is throwing a `TypeError` because it does not call `get_children` with `object`.

```
File "C:\Users\...\.edm\envs\...\lib\site-packages\traitsui\tree_node.py", line 249, in insert_child
    children = self.get_children()
TypeError: get_children() missing 1 required positional argument: 'object'
```

Opening a PR shortly to fix it.

### PR DESCRIPTION
**Pull request by tmreay**
fixes #559

### CODE REVIEW

**Comment by mdickinson** [comment]
Thanks for the fix. How hard would it be to write a regression test?

**Comment by tmreay** [comment]
> Thanks for the fix. How hard would it be to write a regression test?

Sure, where does that best fit? Somewhere in `tests/editors/test_tree_editor.py`?

**Comment by mdickinson** [comment]
Yes, that doesn't look like a bad place to me (but it's really @corranwebster's call,  and he may decide that this doesn't need a test at all).

**Comment by corranwebster** [comment]
Yes `tests/editors/test_tree_editor.py` would be OK, as would be creating a `tests/test_tree_node.py` since you can probably regression test this without a full editor set-up.

**Comment by tmreay** [comment]
Sounds good, I prefer the `test_tree_node.py` route. Currently working on-site with a customer, but I should have time to finish this up over the weekend.

**Comment by tmreay** [comment]
Test has been added, but I'm having trouble verifying that it was actually ran by CI. Is there something I need to do to get the test to be discovered?

**Comment by corranwebster** [comment]
From the logs:
```
test_insert_child (traitsui.tests.test_tree_node.TestTreeNode) ... ok
```
So it is being run.

This LGTM.

**Pull request merged**
