### PR TITLE
Update docs for 7.4.0

### PR DESCRIPTION
**Pull request by corranwebster**
Update documentation on gh-pages.

**Checklist**
- [ ] ~Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~

### CODE REVIEW

**Comment by mdickinson** [comment]
Console error while viewing the docs locally:
```
::1 - - [29/Jun/2022 12:03:20] "GET /_static/fonts/SourceCodePro-Semibold.otf.woff HTTP/1.1" 200 -
::1 - - [29/Jun/2022 12:03:20] code 404, message File not found
::1 - - [29/Jun/2022 12:03:20] "GET /img/glyphicons-halflings.png HTTP/1.1" 404 -
```

**Comment by mdickinson** [comment]
Other than that 404, which isn't having any noticeable effect on the display for me, LGTM.

**Comment by corranwebster** [comment]
> ```::1 - - [29/Jun/2022 12:03:20] "GET /img/glyphicons-halflings.png HTTP/1.1" 404 -```

Possibly a bug in the Enthought Sphinx Style?  I'll look into it.

**Review by mdickinson — APPROVED** [review]
LGTM

**Comment by corranwebster** [comment]
Yep - at first glance it looks like the files are there but the CSS has the wrong path in Enthought Sphinx Theme

**Pull request merged**
