### PR TITLE
Python 3 compatibility and Travis integration

### PR DESCRIPTION
**Pull request by pradyunsg**
This PR adds Python 3 compatibility to TraitsUI. 

Major Changes:
 - Use provides instead of implements
 - Changed Travis CI flow. Uses PySide wheels instead of apt-get to get Qt. (Wheels are hosted at a temporary location)
 - Carrying changes from burnpanck's fork.
 - Minor string-bytes issues.

### CODE REVIEW

**Comment by jf---** [comment]
Have you considered Qt5 support, rather than Qt4? Could that be killing two birds with one stone?

**Comment by jdmarch** [comment]
@jt -  Yes, we very much want to support Qt5. Some implementation obstacles -- PySide does not support Qt5, and it's not clear that it ever will. And PyQt has significant licensing problems such that some users simply can't use it.

**Comment by mdickinson** [comment]
Support for Qt5 and for Python 3 are pretty much orthogonal, though: I don't think it makes sense to try to combine those goals in a single PR.

**Comment by blink1073** [comment]
@mdickinson, agreed.  This is the only library preventing me from moving to Python 3 at work.

**Comment by blink1073** [comment]
FWIW @jdmarch, here's how matplotlib handles it: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/qt_compat.py

**Comment by blink1073** [comment]
@corranwebster, what is the Qt4 on Python 3 issue, perhaps I can lend a hand.

**Comment by jf---** [comment]
@blink1073 excellent reference wrt MPL's handling of Qt compatibility

**Comment by blink1073** [comment]
Since scikit-image has MPL as a dependency, we just use that file directly.

**Comment by pankajp** [comment]
IIRC the Qt5 issue is not relevant to this PR.
The issue here is that someone (most likely from Enthought) has to build and upload pyside eggs/wheels on a public place (say in Enthought's pyside github repo's releases) where it is accessible by travis for running the tests for all python versions we support.
We cannot rely on pyside wheels on a personal repo for the travis tests.
The second point in the PR description `Wheels are hosted at a temporary location` should be fixed to host wheels on a suitable place ( https://github.com/enthought/traitsui/pull/165#issuecomment-67904173 ).

**Comment by corranwebster** [comment]
@blink1073 Sorry for the late reply - and that the comment that was without some context that had been happening in other places.

As @pankajp notes the issue is with getting Travis CI or similar automated testing running using Qt4 & Python 3.  When I last checked Travis CI only had images which had Python 2.7 + Qt4 out of the box; otherwise you needed to somehow install Qt4 and PySide or PyQt for your testing virtual environment.

Building from scratch is impractical, so we need some robust way to get eggs/wheels/etc. installed in the test VMs that is publicly open (we have ways of doing this for Enthought's internal CI, but they require private credentials).

**Comment by blink1073** [comment]
@corranwebster, we use a Rackspace account for scikit-image with PySide wheels that we have built.  The build repo is [here](https://github.com/matthew-brett/travis-wheel-builder), and our Travis script is [here](https://github.com/scikit-image/scikit-image/blob/master/tools/travis_before_install.sh).

**Comment by corranwebster** [comment]
This is now merged into master via #230.  Thanks for everyone's contributions!

**Pull request merged**
