### PR TITLE
Invalidate appveyor build cache

### PR DESCRIPTION
**Pull request by kitchoi**
The CI build now has new EDM dependencies that on the previous build, we keep downloading them rather than restoring them from cache. I believe this was because the cache has not been invalidated: The file uses for keeping track of this requires manual update. This PR updates the file to invalidate the cache.

### CODE REVIEW

**Comment by kitchoi** [comment]
First job on Appveyor failed with just two lines:
```
[00:00:00] Build started
[00:00:03] Command exited with code 1
```
Trying again...

**Comment by mdickinson** [comment]
Caching probably isn't working on macOS:
```
Updating build cache...
Cache entry not found: /Users/appveyor/projects/traitsui/C:/Users/appveyor/.cache
Cache entry not found: /Users/appveyor/projects/traitsui/C:/Users/appveyor/AppData/Local/pip/Cache
Cache '/Users/appveyor/cache' - Updated
```

**Comment by kitchoi** [comment]
I think the last line `'/Users/appveyor/cache'` was specifically added for OSX in #1160. Looks like we are just ignoring the two Windows paths as being harmless (albeit ugly)...

**Comment by mdickinson** [comment]
Fair enough. `/Users/appveyor/cache` excludes EDM's package cache, though, doesn't it? (I'm not sure, and `edm cache info` currently crashes on my machine.)

**Comment by kitchoi** [comment]
I am not sure actually. From the difference in the [build](https://ci.appveyor.com/project/EnthoughtOSS/traitsui/builds/35403476/job/w4tp0jg55h6t540d) on this PR and the last [build](https://ci.appveyor.com/project/EnthoughtOSS/traitsui/builds/35402847/job/4myjhn90o21s9ql4) before this PR, I guess the cache was working because some packages are not downloaded.

**Comment by kitchoi** [comment]
I think that's probably what this line is doing:
https://github.com/enthought/traitsui/blob/38daaa8f17d7c229f3e34871660ea8330ad4490e/appveyor.yml#L49
It redirects the cache directory there. I think EDM uses this environment variable.

**Comment by mdickinson** [comment]
> From the difference in the [build](https://ci.appveyor.com/project/EnthoughtOSS/traitsui/builds/35403476/job/w4tp0jg55h6t540d) on this PR and the last [build](https://ci.appveyor.com/project/EnthoughtOSS/traitsui/builds/35402847/job/4myjhn90o21s9ql4) before this PR, I guess the cache was working because some packages are not downloaded.

Hmm. I'm not convinced: I see downloads in both cases. I suspect differences in the details are probably just due to timings of when the output was captured.

EDM's download cache is under `~/.cache`, I believe; I don't see anywhere in the Appveyor config that would be caching that. (Unless it automatically caches `~/.cache` regardless of config?)

**Comment by kitchoi** [comment]
I dived into EDM source and it seems that EDM uses the environment variable `XDG_CACHE_HOME` for caching if it is set, if it is not set then it would use `~/.cache` indeed.

**Comment by mdickinson** [comment]
> EDM uses the environment variable `XDG_CACHE_HOME` for caching if it is set

Ah, cool! Didn't realise that.

**Comment by kitchoi** [comment]
The cache has been invalidated by running CI with this PR. Another PR is now making use of the new cache. Closing without merging.

**Pull request closed without merging**
