### PR TITLE
Automated PEP8 Reformatting

### PR DESCRIPTION
**Pull request by corranwebster**
Running autopep8 over the traitsui codebase in an attempt to make things a bit more standard.

I may end up throwing this away if it doesn't look good.

### CODE REVIEW

**Comment by corranwebster** [comment]
Looks like autopep8 misses the space in `class Foo (Bar):`.

**Comment by stevenjkern** [comment]
I love it, personally. I think the spaces left in class definitions should be easy to fix with a carefully crafted `awk sed`.

**Comment by corranwebster** [comment]
Yes, I'm sure we can fix the class stuff in an automated way.

There's also some line-wrapping awkwardness in places like https://github.com/enthought/traitsui/pull/290/files#diff-3cb71a10e4229dc2d036f40ad8484a3cR230 and also where there are many imports, like https://github.com/enthought/traitsui/blob/enh/pep8ify-traitsui/traitsui/ui.py#L31

In two minds about this, as it would be nice if this could be applied with a minimum of manual fix-ups.

**Comment by mdickinson** [comment]
+1 for applying this exactly as it is, and doing manual fix-ups in a separate PR. (Rationale: it should be safe to merge this PR with minimal review based on randomly sampling the changes; manual fix-ups should require a one-notch higher review level.)

**Comment by jonathanrocher** [comment]
+1!

**Comment by corranwebster** [comment]
Did an automated multi-file search/replace for `class Foo (` patterns.

Would like a quick look over, and want the tests to pass, but I think this is probably good.

**Comment by corranwebster** [comment]
@itziakos Verbally gave blessing.  Merging.

**Pull request merged**
