### PR TITLE
Build CI on maintenance branches

### PR DESCRIPTION
**Pull request by corranwebster**
We aren't getting CI builds on maintenance branches.

### CODE REVIEW

**Comment by mdickinson** [comment]
Would it be simpler to just drop the branch restriction altogether?

**Comment by corranwebster** [comment]
I was getting double builds - one for the branch and one for the PR merge - when I removed all branch restrictions.  That seems overkill.

**Comment by mdickinson** [comment]
> I was getting double builds - one for the branch and one for the PR merge - when I removed all branch restrictions. That seems overkill.

Yes, that's overkill: we only need the PR build. But it's configurable: for Travis, this is configurable through the settings; for Appveyor, it's configurable through the webhook.

**Comment by mdickinson** [comment]
> But it's configurable:

FWIW, I've configured both Travis CI and Appveyor only to build for pull requests for this repository.

**Pull request merged**
