### PR TITLE
Fix pypi installation

### PR DESCRIPTION
**Pull request by itziakos**
This PR against the maintenance branch 4.5.x fixes issue #206

### CODE REVIEW

**Comment by itziakos** [comment]
@corranwebster, please have a look

**Comment by itziakos** [comment]
I will need to make a separate PR for the master branch

**Comment by cournape** [comment]
Wouldn't it make more sense to first push the fix in master and then cherry-pick in the maintenance branch(es) ?

**Comment by cournape** [comment]
The change LGTM otherwise

**Comment by sjagoe** [comment]
@itziakos Please make the fix against master first, then backport to maintenance.

cc @cournape

**Comment by corranwebster** [comment]
Yep - copy pasta.  LGTM, but yes, should fix master first.

**Comment by corranwebster** [comment]
Closed in favour of #210

**Pull request closed without merging**
