### PR TITLE
Fix Qt date editor problem with None value for date

### LINKED ISSUE #967: Qt simple DateEditor view shows a date despite the underlying value being none
Initially mentioned in #962, to reproduce:

```
from traits.api import Date, HasTraits
from traitsui.api import UItem, View, DateEditor

class Model(HasTraits):

    date = Date()

    def default_traits_view(self):
        return View(
            UItem('date', editor=DateEditor())
        )

model = Model(date=None)

if __name__ == '__main__':
    model.configure_traits()
```

On Mac OSX, the view shows this:
Screenshot 2020-07-06 at 11 08 14

This is misleading as the underlying value is `None`.

### PR DESCRIPTION
**Pull request by aaronayres35**
fixes #967 

See the comments on #967 for more details.

### CODE REVIEW

**Comment by kitchoi** [comment]
I can reproduce the test error in the PySide2 environment with OSX installed from `etstool.py`.
But if I create another environment and install `PySide2` from PyPI, I get PySide2 5.15.0 instead of PySide2 5.11.0, and the test passes there.

This is how I install another environment with a new PySide2
```
$ python3.8 -m venv ~/my_favourite_folder_for_venvs/pyside2-env
$ source ~/my_favourite_folder_for_venvs/pyside2-env/bin/activate
$ pip install .[pyside2]   # in traitsui source root folder
```

Do you mind confirming if you observe the same behaviour please?

**Comment by aaronayres35** [comment]
> I can reproduce the test error in the PySide2 environment with OSX installed from `etstool.py`.
> But if I create another environment and install `PySide2` from PyPI, I get PySide2 5.15.0 instead of PySide2 5.11.0, and the test passes there.
> 
> This is how I install another environment with a new PySide2
> 
> ```
> $ python3.8 -m venv ~/my_favourite_folder_for_venvs/pyside2-env
> $ source ~/my_favourite_folder_for_venvs/pyside2-env/bin/activate
> $ pip install .[pyside2]   # in traitsui source root folder
> ```
> 
> Do you mind confirming if you observe the same behaviour please?

When I followed your instructions I got that the test passed as well

**Comment by kitchoi** [comment]
Currently the `etstool.py` (used by CI) is pinning PySide2 5.11:
https://github.com/enthought/traitsui/blob/88f4cd8887c36cf5916b8f551594156c705bc420/etstool.py#L204

**Comment by kitchoi** [comment]
Despite the test passes with a newer version of PySide2, I can't verify that this fixes the issue in #967 when I ran the script provided there. @aaronayres35 Have you tried?

**Comment by kitchoi** [comment]
Actually, now I realize that my idea of using `GUI.invoke_later` is a worse workaround than the one in https://forum.qt.io/topic/3068/solved-enhancing-qdateedit-to-allow-for-null-empty-dates/17
The reason is that we could not make sure when the callable provided in `GUI.invoke_later` is called by the event loop, the `QDateEdit` has not been destroyed. For example, the `init` could be called and then the editor be disposed of all without having started the GUI event loop. Then the GUI event loop may start for other reasons, and the callable will raise because it would try to access `self.control` which is no longer valid. This is probably rare (or not a use case) but can happen.

Now I think perhaps we should close this and try something else. @aaronayres35, would that be okay? I am sorry about this.

**Comment by aaronayres35** [comment]
> Actually, now I realize that my idea of using `GUI.invoke_later` is a worse workaround than the one in https://forum.qt.io/topic/3068/solved-enhancing-qdateedit-to-allow-for-null-empty-dates/17
> The reason is that we could not make sure when the callable provided in `GUI.invoke_later` is called by the event loop, the `QDateEdit` has not been destroyed. For example, the `init` could be called and then the editor be disposed of all without having started the GUI event loop. Then the GUI event loop may start for other reasons, and the callable will raise because it would try to access `self.control` which is no longer valid. This is probably rare (or not a use case) but can happen.
> 
> Now I think perhaps we should close this and try something else. @aaronayres35, would that be okay? I am sorry about this.

Yeah that is okay with me, I will close this now.

**Comment by kitchoi** [comment]
Thanks.

**Pull request closed without merging**
