### PR TITLE
Fix regression with `BoundsEditor` introduced when removing deprecated `format` trait

### PR DESCRIPTION
**Pull request by ericpre**
Regression introduced in https://github.com/enthought/traitsui/pull/2002.

**Checklist**
- [ ] Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)

### CODE REVIEW

**Comment by ericpre** [comment]
Could the test suite failure be related to pyside6 6.5.1? matploltib and pyqtgraph also have test suite failure with this version.

**Review by corranwebster — APPROVED** [review]
This looks good, and upstream issues with tests should now be resolved.

**Comment by corranwebster** [comment]
Thanks for the contribution!

**Comment by janlimbeck** [comment]
@corranwebster When will a new version of traitsui be released? It would be good to have e.g. the fix of this PR in an official version.

**Pull request merged**
